### ISSUE TITLE
Invalid download data for LINCS Level 3

### ISSUE THREAD

**Issue by srp33** [srp33/Geney#15]
Recently, we posted LINCS data on the public facing server. These are very large datasets. I ran some tests, and the behavior suggests there is a bug. Below are steps to reproduce the error:

1. Browse to http://45.56.87.243/dataset/LINCS_PhaseII_Level3
2. Click on Select Samples.
3. Select primary_site as the variable to filter on.
4. Specify large intestine, liver, and lung. Click on Confirm. It says, "You have selected 91133 samples." Keep primary_site as the selected variable to download.
5. Select DDR1 and PAX8 as genes.
6. Click on Download. The resulting file only has 25 rows of data.

This result seems to occur also when I filter on different metadata or select different genes.

**Comment by pjtatlow** [comment]
So I've copied this dataset to my laptop and tried running the same query. I started printing out the times that each operating was taking per sample (reading from sqlite and reading from hdf5). On my laptop which has a good SSD, it's taking anywhere between 500 and 750ms to read the metadata for one sample from the SQLite file, and about 1 ms to read from the HDF5. It doesn't look like linode servers have SSD's, so those times are probably a lot larger on the actual server, and I think it's just timing out. On my machine it goes past 25, but it takes a very long time. We should probably revisit which columns we're putting indexes on and see if that can help.

**Comment by srp33** [comment]
Thanks for the update.

According to the Linode web site, they use SSD drives (only), but maybe they are a lot slower than what you have on your system.

Yesterday I assigned one of my students (with a CS background) to work on optimizing SQLite (or replacing it with something else). Hopefully he will improve the speed soon. It might even be worth trying it with the metadata in a JSON file and read the whole thing into memory (on the back end) as a nested dictionary instead of SQLite. We may try that.

However, I don't really like that Geney will spit out a partial file if it times out. Can we a) increase the timeout and b) have it display an error message if it times out?

Thanks!

--
Stephen Piccolo, PhD
Assistant Professor
Department of Biology
Brigham Young University

Office: 4056 LSB
Email: stephen_piccolo@byu.edu
Phone: 801-422-7116
Web: https://piccolo.byu.edu
Twitter: @stevepiccolo

**Comment by pjtatlow** [comment]
It might be possible to increase the timeout, but it doesn't look like Flask gives us a way to do that directly so I might have to start digging around in their source code to make that work. Unfortunately, there isn't a way to display an error when it times out because the server already started serving the response and sent a status code of `200` meaning everything's fine.

**Comment by srp33** [comment]
I think we can close this now. We've completely reworked the way the data are stored and queried. We'll do some thorough testing of all the datasets soon.
