### ISSUE TITLE
Change metadata.pkl to key-value store?

### ISSUE THREAD

**Issue by srp33** [srp33/Geney#23]
Currently, we store metadata about the datasets in a pickle file on the back end. We should consider changing this to a key-value store so we don't need to load the whole file into memory to get the information we need. @kimballh @pjtatlow

**Comment by pjtatlow** [comment]
I think the json file is just sent to the front end as a static file, but I could be wrong.

**Comment by srp33** [comment]
Yeah, I was thinking of the pickle file.


----------------------------------------------
Stephen Piccolo, PhD
Assistant Professor
Department of Biology
Brigham Young University

Office: 4056 LSB
Email: stephen_piccolo@byu.edu
Phone: 801-422-7116
Web: https://piccolo.byu.edu
Twitter: @stevepiccolo

**Comment by pjtatlow** [comment]
Is that this download history thing? I'm not sure I know what that is!

**Comment by srp33** [comment]
It stores the data type, max, min, unique values, etc. for each variable.
We only need this information for each variable at a time, so we could put
this in a key-value store on the backend. Then it could grab this metadata
just for one variable at a time rather than having to load the full object
into memory to grab data for the variable being used for filtering on the
front end.

By the way, we've been working through some issues on the backend, and
hopefully Geney queries will be much faster after these upcoming changes.


----------------------------------------------
Stephen Piccolo, PhD
Assistant Professor
Department of Biology
Brigham Young University

Office: 4056 LSB
Email: stephen_piccolo@byu.edu
Phone: 801-422-7116
Web: https://piccolo.byu.edu
Twitter: @stevepiccolo

**Comment by srp33** [comment]
This has been resolved.
