### ISSUE TITLE
Unable to retrieve number of samples for LINCS data

### ISSUE THREAD

**Issue by srp33** [srp33/Geney#31]
The screenshots below are an example where I'm getting an error when trying to download LINCS data. On the "Filter Features" page, it says "Unable to retreive number of samples." Please see if you can replicate this and find the cause of the problem. Let me know if I need to modify any code in the middle layer.

![image](https://user-images.githubusercontent.com/12720/60106384-60c95400-9722-11e9-8715-3bc0d5b4bf76.png)
![image](https://user-images.githubusercontent.com/12720/60106402-69218f00-9722-11e9-8038-0361025443a4.png)

**Comment by kimballh** [comment]
I am getting this error:

  File "/app/app.py", line 184, in get_samples
    count, file = dataset.save_sample_indices_matching_filters(discrete_filters, numeric_filters)
  File "/app/data_access/DataSetParser.py", line 105, in save_sample_indices_matching_filters
    keep_row_indices = [str(x).encode() for x in keep_row_indices]
  File "/app/data_access/DataSetParser.py", line 105, in <listcomp>
    keep_row_indices = [str(x).encode() for x in keep_row_indices]
  File "/app/data_access/DataSetParser.py", line 349, in filter_rows_numeric
    if operator_dict[the_filter.operator](fastnumbers.float(value), the_filter.query_value):
ValueError: could not convert string to float: b'NA'

I am looking into the most efficient way to handle it.

**Comment by srp33** [comment]
Resolved. Thanks!
