### ISSUE TITLE
Going back and then forward doesn't remember options on Download page

### ISSUE THREAD

**Issue by srp33** [srp33/Geney#5]
Steps to reproduce this:

1. Select some specific genes on the Download page
2. Change it to Select All Genes.
3. Click on Back.
4. Click on Confirm (which takes me to the Download page again)
5. It shows the specific genes that I selected in step 1 rather than Select All Genes.

How feasible would it be to fix this?

**Comment by pjtatlow** [comment]
Fixed in PR #8
