### ISSUE TITLE
GSE62944 not including as much data as it should

### ISSUE THREAD

**Issue by srp33** [srp33/Geney#6]
For example, when I choose breast cancer (BRCA), it only gives me data for about 110 patients. But it should be more like 1000. Please look at the data and see whether it's a problem with the data or a problem with the app. If it's a problem with the data, please let me know so I can track down the source of the problem.

**Comment by pjtatlow** [comment]
Both datasets ( the Normal_TPM and the FeatureCounts ) only have 113 BRCA samples, so the site is working correctly. I'd look for an issue in the data processing if we're losing samples somewhere.
